[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ectf25_design"
version = "0.1"
requires-python = ">=3.11"

# dependencies managed in `setup.py`
dynamic = ["dependencies"]

[project.optional-dependencies]
dev = [
    "ruff"
]
