# Shim / wrapper around build.sh script

BUILD = ./build.sh

.PHONY: all build clean format debug

all: build

build:
	$(BUILD) build

clean:
	$(BUILD) clean

format:
	$(BUILD) format

debug:
	$(BUILD) debug
